'use client';

import { ExternalLink, Quote, Star } from 'lucide-react';

interface Testimonial { authorName: string; authorRole: string | null; authorCompany: string | null; authorAvatarUrl: string | null; quote: string; rating: number | null; sourceUrl: string | null }
interface TestimonialsProps { testimonials: Testimonial[] }

export function Testimonials({ testimonials }: TestimonialsProps) {
  if (!testimonials.length) return null;
  return <section id="testimonials" className="mx-auto max-w-[90rem] px-5 py-20 md:px-10 lg:py-32"><div className="mb-12"><p className="section-kicker">06 / Testimonials</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-white md:text-6xl">Kind words from good people.</h2></div><div className="grid gap-4 lg:grid-cols-3">{testimonials.map((testimonial) => <figure key={`${testimonial.authorName}-${testimonial.quote}`} className="relative flex min-h-72 flex-col rounded-[2rem] border border-white/10 bg-white/[0.045] p-7 md:p-8"><Quote className="mb-5 h-7 w-7 text-cyan-200" /><blockquote className="text-lg leading-8 tracking-[-0.01em] text-slate-200">“{testimonial.quote}”</blockquote><figcaption className="mt-auto flex items-end justify-between gap-3 pt-8"><div className="flex items-center gap-3">{testimonial.authorAvatarUrl ? <img src={testimonial.authorAvatarUrl} alt="" className="h-10 w-10 rounded-full object-cover" /> : <span className="grid h-10 w-10 place-items-center rounded-full bg-cyan-200/10 text-sm font-bold text-cyan-100">{testimonial.authorName[0]}</span>}<div><p className="text-sm font-bold text-white">{testimonial.authorName}</p><p className="text-xs text-slate-500">{[testimonial.authorRole, testimonial.authorCompany].filter(Boolean).join(' · ')}</p></div></div><div>{testimonial.rating && <div className="flex gap-0.5 text-cyan-200">{Array.from({ length: testimonial.rating }, (_, index) => <Star key={index} className="h-3 w-3 fill-current" />)}</div>}{testimonial.sourceUrl && <a href={testimonial.sourceUrl} target="_blank" rel="noopener noreferrer" aria-label="View testimonial source" className="mt-2 inline-flex text-slate-400 hover:text-white"><ExternalLink className="h-4 w-4" /></a>}</div></figcaption></figure>)}</div></section>;
}
